<a href="https://colab.research.google.com/github/Camillabgarcia/Python-para-Data-Science/blob/main/pandas_transformacao_manipulacao_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
dados = pd.read_json('/content/drive/MyDrive/dados_hospedagem (1).json')
dados.head()

                                         info_moveis
0  {'avaliacao_geral': '10.0', 'experiencia_local...
1  {'avaliacao_geral': '10.0', 'experiencia_local...
2  {'avaliacao_geral': '10.0', 'experiencia_local...
3  {'avaliacao_geral': '10.0', 'experiencia_local...
4  {'avaliacao_geral': '10.0', 'experiencia_local...

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Temos uma visualização de como é o nosso arquivo, na qual percebemos que os dados estão aninhados em formato de dicionário. Para estudá-los e identificar onde podemos prepará-los, tratá-los e transformá-los, precisamos que estejam destrinchados.

utilizaremos o método json_normalize() que fará exatamente o que precisamos: a normalização desses dados — neste caso, da coluna info_moveis.

In [5]:
dados = pd.json_normalize(dados['info_moveis'])
dados

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,nan,--,5,[Our cozy little bungalow is the perfect place...,[The Queen Anne neighborhood is one of the mos...,"[1, 3, 2, 2, 2, 1, 2, 1, 1, 1, 2, 3, 2, 2, 2, ...","[2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, ...","[3, 2, 2, 3, 3, 2, 3, 2, 2, 3, 3, 3, 2, 3, 2, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{""Cable TV"",""Wireless Internet"",Kitchen,""Free...","[$250.00, $200.00, $0, $0, $0, $200.00, $350.0...","[$35.00, $50.00, $100.00, $100.00, $0, $30.00,...","[$150.00, $200.00, $143.00, $150.00, $350.00, ..."
66,nan,--,6,[Bright clean 2 bedroom 1 bath appartment in t...,[Ballard is the most interesting and ecclectic...,"[1, 1, 3, 2, 1, 3, 2, 2, 1, 2, 2, 2, 1, 2, 1, ...","[2, 3, 3, 2, 2, 3, 2, 3, 2, 2, 2, 2, 4, 3, 3, ...","[3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 2, 4, 4, 3, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",K...","[$200.00, $200.00, $100.00, $0, $0, $750.00, $...","[$0, $0, $100.00, $0, $75.00, $140.00, $112.00...","[$99.00, $185.00, $250.00, $200.00, $275.00, $..."
67,nan,--,7,[Beautiful end-unit townhome with lots of dayl...,"[Cherry blossoms (Sakura) in the spring, every...","[4, 3, 1, 2, 2, 1, 2, 1, 2, 2]","[3, 4, 3, 3, 3, 3, 3, 3, 3, 4]","[3, 5, 1, 5, 3, 2, 3, 4, 4, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$750.00, $350.00, $500.00, $500.00, $0, $200....","[$300.00, $90.00, $250.00, $100.00, $109.00, $...","[$218.00, $350.00, $450.00, $149.00, $99.00, $..."
68,nan,--,8,[Heart of Ballard new townhome with 4 BRs + ba...,"[--, --, The suite is conveniently located off...","[2, 2, 3, 1, 1, 2, 1, 3, 2, 1, 2, 1, 2, 2, 2, ...","[4, 2, 3, 4, 3, 3, 4, 4, 3, 5, 2, 3, 3, 4, 5, ...","[4, 4, 3, 3, 5, 5, 5, 5, 3, 5, 4, 5, 5, 4, 1, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",""Air Conditi...","[$500.00, $150.00, $250.00, $800.00, $0, $500....","[$50.00, $85.00, $150.00, $75.00, $100.00, $80...","[$275.00, $199.00, $400.00, $325.00, $300.00, ..."
69,nan,--,9,[This business-themed modern home features: *...,[Your hosts made Madison Valley their home whe...,"[2, 1]","[3, 4]","[6, 6]","[Real Bed, Real Bed]","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00, $500.00]","[$150.00, $0]","[$250.00, $350.00]"

Anteriormente, conhecemos nossos dados e observamos que em algumas colunas temos dados agrupados em listas. Para facilitar o acesso à esses dados a fim de que possamos trabalhá-los, precisamos desagrupá-los.

**Coletando os nomes das colunas**

Listagem dos nomes de todas as colunas do dataframe.

In [6]:
colunas = list(dados.columns)
colunas

['avaliacao_geral',
 'experiencia_local',
 'max_hospedes',
 'descricao_local',
 'descricao_vizinhanca',
 'quantidade_banheiros',
 'quantidade_quartos',
 'quantidade_camas',
 'modelo_cama',
 'comodidades',
 'taxa_deposito',
 'taxa_limpeza',
 'preco']

**Desagrupando os dados**

Para desagrupar esses dados, podemos utilizar o método .explode(), que separa as informações em linhas. Ele requer que enviemos o nome das colunas que serão transformadas, então o primeiro passo é coletar esses nomes.

In [7]:
dados = dados.explode(colunas[3:])
dados

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
68,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
68,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
69,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
69,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

**Resetendo os índices para ordenar os dados.**

Para isso usaremos o método reset_index() passando os parâmetros inplace=True e drop=True. O primeiro substitui os índices no dataframe, já o segundo trata-se da criação de uma coluna com os índices antigos, porém, sendo True, não teremos essa criação.

In [8]:
dados.reset_index(inplace=True, drop=True)
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

**Verificando os tipos de dados.**

É possível notar as características dos dados do nosso dataframe: há textos e números inteiros e float. Mas precisamos garantir que estejam com a tipagem correta para que possamos utilizá-los em tratamentos futuros.

Para isso, usaremos o método .info(), que nos retorna os tipos de dados.

In [9]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

Temos várias colunas do tipo object, a transformação da tipagem precisa ser feita manualmente, pois para trabalharmos com estatística, por exemplo, precisamos que os dados numéricos sejam corretamente tipados como números.

**Tratando dados numéricos: convertendo para tipo inteiro**

Usaremos o método .astype(), que converte colunas para um tipo específico de dado. Mas, primeiro, importaremos a biblioteca NumPy, que nos fornecerá um tipo de dado (inteiro e float) para podermos converter as colunas numéricas no nosso dataframe.

Alterando o tipo:

In [10]:
import numpy as np

In [11]:
dados['max_hospedes'].astype(np.int64)

0       1
1       1
2       1
3       1
4       1
       ..
3813    8
3814    8
3815    8
3816    9
3817    9
Name: max_hospedes, Length: 3818, dtype: int64

 Atribuição desses dados para a coluna "max_hospedes":

In [12]:
dados['max_hospedes'] = dados['max_hospedes'].astype(np.int64)

Para certificar que os dados foram corretamente substituídos, foi solicitado a tipagem das colunas:

In [13]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: int64(1), object(12)
memory usage: 387.9+ KB

Lista com as colunas cujos dados devem ser do tipo inteiro :

In [14]:
col_numericas = ['quantidade_banheiros', 'quantidade_quartos', 'quantidade_camas']

Aplicando o mesmo processo realizado para "max_hospedes" :

In [15]:
dados[col_numericas] = dados[col_numericas].astype(np.int64)

In [16]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: int64(4), object(9)
memory usage: 387.9+ KB

**Tratando dados numéricos: convertendo para tipo float**

A coluna "avaliacao_geral" deve ser do tipo float, então foi feito um processo semelhante, mas agora convertendo para float64:

In [17]:
dados['avaliacao_geral'] = dados['avaliacao_geral'].astype(np.float64)

Verificando se as colunas foram alteradas :

In [18]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

O .astype() vai funcionar em dados com cifrão ($) e vírgula (,) nas colunas "taxa_deposito", "taxa_limpeza" e "preco" são do tipo float porque correspondem a valores de moeda?

In [19]:
dados['preco'] = dados['preco'].astype(np.float64)

ValueError: could not convert string to float: '$110.00'

Focando no tratamento da coluna "preco" que, por conter caracteres como cifrão e vírgula, não pode ser convertido para o tipo float.

In [20]:
dados['preco']

0       $110.00
1        $45.00
2        $55.00
3        $52.00
4        $85.00
         ...
3813    $299.00
3814    $199.00
3815    $400.00
3816    $250.00
3817    $350.00
Name: preco, Length: 3818, dtype: object

Cada elemento dessa coluna é uma string, então podemos fazer uma função que passe linha por linha para remover os caracteres.

Para isso, usaremos o método .apply() com lambda, que aplica uma função específica a cada elemento, no caso, a remoção dos caracteres. Feito isso, usaremos o método .replace() para substituir os caracteres de cifrão e vírgula por nada, ou seja, por uma string vazia. Depois, usaremos .strip() para remover qualquer caractere antes ou depois do elemento.

In [22]:
dados['preco'].apply(lambda x: x.replace('$', '').replace(',', '').strip())

0       110.00
1        45.00
2        55.00
3        52.00
4        85.00
         ...
3813    299.00
3814    199.00
3815    400.00
3816    250.00
3817    350.00
Name: preco, Length: 3818, dtype: object

Atribundo as alterações ao dataframe original:

In [23]:
dados['preco'] = dados['preco'].apply(lambda x: x.replace('$', '').replace(',', '').strip())

Usando astype depois do tratamento :

In [24]:
dados['preco'] = dados['preco'].astype(np.float64)

In [25]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

Conversão de duas colunas : "taxa_deposito" e "taxa_limpeza".

In [27]:
dados[['taxa_deposito', 'taxa_limpeza']]

     taxa_deposito taxa_limpeza
0               $0           $0
1               $0           $0
2               $0           $0
3               $0       $20.00
4               $0       $15.00
...            ...          ...
3813     $1,000.00      $178.00
3814            $0       $99.00
3815            $0           $0
3816     $1,000.00      $150.00
3817       $500.00           $0

[3818 rows x 2 columns]

Quando tratamos da conversão de um dataframe, no qual passaremos por cada elemento, é mais viável utilizarmos o método .applymap():

In [28]:
dados[['taxa_deposito', 'taxa_limpeza']].applymap(lambda x: x.replace('$', '').replace(',', '').strip())

     taxa_deposito taxa_limpeza
0                0            0
1                0            0
2                0            0
3                0        20.00
4                0        15.00
...            ...          ...
3813       1000.00       178.00
3814             0        99.00
3815             0            0
3816       1000.00       150.00
3817        500.00            0

[3818 rows x 2 columns]

Atribundo as alterações ao dataframe original:

In [29]:
dados[['taxa_deposito', 'taxa_limpeza']] = dados[['taxa_deposito', 'taxa_limpeza']].applymap(lambda x: x.replace('$', '').replace(',', '').strip())

Usando astype depois do tratamento :

In [30]:
dados[['taxa_deposito', 'taxa_limpeza']] = dados[['taxa_deposito', 'taxa_limpeza']].astype(np.float64)

In [31]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   float64
 11  taxa_limpeza          3818 non-null   float64
 12  preco                 3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB